{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Apr 17 11:52:26 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",556,131,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(10.27027,-0.03918457,64.32432,0.02734845);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.18);
   c1->SetRightMargin(0.08);
   c1->SetTopMargin(0.07);
   c1->SetBottomMargin(0.17);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderSize(0);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderSize(0);
   
   TH1D *EffTruth_diff_frac = new TH1D("EffTruth_diff_frac","",8,20,60);
   EffTruth_diff_frac->SetBinContent(1,-0.01138224);
   EffTruth_diff_frac->SetBinContent(2,-0.009039816);
   EffTruth_diff_frac->SetBinContent(3,-0.01408377);
   EffTruth_diff_frac->SetBinContent(4,-0.01039199);
   EffTruth_diff_frac->SetBinContent(5,-0.007980618);
   EffTruth_diff_frac->SetBinContent(6,-0.004669251);
   EffTruth_diff_frac->SetBinContent(7,-0.004910972);
   EffTruth_diff_frac->SetBinContent(8,-0.007609653);
   EffTruth_diff_frac->SetBinContent(9,-0.0009492409);
   EffTruth_diff_frac->SetBinError(1,0.004494793);
   EffTruth_diff_frac->SetBinError(2,0.003702132);
   EffTruth_diff_frac->SetBinError(3,0.00328558);
   EffTruth_diff_frac->SetBinError(4,0.003209603);
   EffTruth_diff_frac->SetBinError(5,0.003250268);
   EffTruth_diff_frac->SetBinError(6,0.003462609);
   EffTruth_diff_frac->SetBinError(7,0.003731807);
   EffTruth_diff_frac->SetBinError(8,0.00463162);
   EffTruth_diff_frac->SetBinError(9,0.002752021);
   EffTruth_diff_frac->SetMinimum(-0.02787396);
   EffTruth_diff_frac->SetMaximum(0.02269114);
   EffTruth_diff_frac->SetEntries(0.07006831);
   EffTruth_diff_frac->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#3300cc");
   EffTruth_diff_frac->SetLineColor(ci);

   ci = TColor::GetColor("#3300cc");
   EffTruth_diff_frac->SetMarkerColor(ci);
   EffTruth_diff_frac->SetMarkerStyle(20);
   EffTruth_diff_frac->GetXaxis()->SetTitle("p_{T}^{ref} [GeV]");
   EffTruth_diff_frac->GetXaxis()->SetNdivisions(505);
   EffTruth_diff_frac->GetXaxis()->SetLabelFont(42);
   EffTruth_diff_frac->GetXaxis()->SetLabelSize(0.05);
   EffTruth_diff_frac->GetXaxis()->SetTitleSize(0.05);
   EffTruth_diff_frac->GetXaxis()->SetTitleOffset(1.1);
   EffTruth_diff_frac->GetXaxis()->SetTitleFont(42);
   EffTruth_diff_frac->GetYaxis()->SetTitle("#Delta #epsilon / #epsilon");
   EffTruth_diff_frac->GetYaxis()->SetNdivisions(505);
   EffTruth_diff_frac->GetYaxis()->SetLabelFont(42);
   EffTruth_diff_frac->GetYaxis()->SetLabelSize(0.05);
   EffTruth_diff_frac->GetYaxis()->SetTitleSize(0.05);
   EffTruth_diff_frac->GetYaxis()->SetTitleOffset(1.5);
   EffTruth_diff_frac->GetYaxis()->SetTitleFont(42);
   EffTruth_diff_frac->GetZaxis()->SetNdivisions(707);
   EffTruth_diff_frac->GetZaxis()->SetLabelFont(42);
   EffTruth_diff_frac->GetZaxis()->SetLabelOffset(0.015);
   EffTruth_diff_frac->GetZaxis()->SetLabelSize(0.05);
   EffTruth_diff_frac->GetZaxis()->SetTitleSize(0.05);
   EffTruth_diff_frac->GetZaxis()->SetTitleOffset(1.1);
   EffTruth_diff_frac->GetZaxis()->SetTitleFont(42);
   EffTruth_diff_frac->Draw("EX");
   
   TH1D *EffTruth_diff_frac_smooth = new TH1D("EffTruth_diff_frac_smooth","",8,20,60);
   EffTruth_diff_frac_smooth->SetBinContent(1,-0.01138224);
   EffTruth_diff_frac_smooth->SetBinContent(2,-0.01147919);
   EffTruth_diff_frac_smooth->SetBinContent(3,-0.01094064);
   EffTruth_diff_frac_smooth->SetBinContent(4,-0.009588449);
   EffTruth_diff_frac_smooth->SetBinContent(5,-0.007900479);
   EffTruth_diff_frac_smooth->SetBinContent(6,-0.0067422);
   EffTruth_diff_frac_smooth->SetBinContent(7,-0.006714418);
   EffTruth_diff_frac_smooth->SetBinContent(8,-0.007609653);
   EffTruth_diff_frac_smooth->SetBinContent(9,-0.0009492409);
   EffTruth_diff_frac_smooth->SetBinError(1,0.004494793);
   EffTruth_diff_frac_smooth->SetBinError(2,0.003702132);
   EffTruth_diff_frac_smooth->SetBinError(3,0.00328558);
   EffTruth_diff_frac_smooth->SetBinError(4,0.003209603);
   EffTruth_diff_frac_smooth->SetBinError(5,0.003250268);
   EffTruth_diff_frac_smooth->SetBinError(6,0.003462609);
   EffTruth_diff_frac_smooth->SetBinError(7,0.003731807);
   EffTruth_diff_frac_smooth->SetBinError(8,0.00463162);
   EffTruth_diff_frac_smooth->SetBinError(9,0.002752021);
   EffTruth_diff_frac_smooth->SetMinimum(-0.02787396);
   EffTruth_diff_frac_smooth->SetMaximum(0.02269114);
   EffTruth_diff_frac_smooth->SetEntries(0.07006831);
   EffTruth_diff_frac_smooth->SetStats(0);

   ci = TColor::GetColor("#660066");
   EffTruth_diff_frac_smooth->SetLineColor(ci);

   ci = TColor::GetColor("#660066");
   EffTruth_diff_frac_smooth->SetMarkerColor(ci);
   EffTruth_diff_frac_smooth->SetMarkerStyle(21);
   EffTruth_diff_frac_smooth->GetXaxis()->SetTitle("p_{T}^{ref} [GeV]");
   EffTruth_diff_frac_smooth->GetXaxis()->SetNdivisions(505);
   EffTruth_diff_frac_smooth->GetXaxis()->SetLabelFont(42);
   EffTruth_diff_frac_smooth->GetXaxis()->SetLabelSize(0.05);
   EffTruth_diff_frac_smooth->GetXaxis()->SetTitleSize(0.05);
   EffTruth_diff_frac_smooth->GetXaxis()->SetTitleOffset(1.1);
   EffTruth_diff_frac_smooth->GetXaxis()->SetTitleFont(42);
   EffTruth_diff_frac_smooth->GetYaxis()->SetTitle("#Delta #epsilon / #epsilon");
   EffTruth_diff_frac_smooth->GetYaxis()->SetNdivisions(505);
   EffTruth_diff_frac_smooth->GetYaxis()->SetLabelFont(42);
   EffTruth_diff_frac_smooth->GetYaxis()->SetLabelSize(0.05);
   EffTruth_diff_frac_smooth->GetYaxis()->SetTitleSize(0.05);
   EffTruth_diff_frac_smooth->GetYaxis()->SetTitleOffset(1.5);
   EffTruth_diff_frac_smooth->GetYaxis()->SetTitleFont(42);
   EffTruth_diff_frac_smooth->GetZaxis()->SetNdivisions(707);
   EffTruth_diff_frac_smooth->GetZaxis()->SetLabelFont(42);
   EffTruth_diff_frac_smooth->GetZaxis()->SetLabelOffset(0.015);
   EffTruth_diff_frac_smooth->GetZaxis()->SetLabelSize(0.05);
   EffTruth_diff_frac_smooth->GetZaxis()->SetTitleSize(0.05);
   EffTruth_diff_frac_smooth->GetZaxis()->SetTitleOffset(1.1);
   EffTruth_diff_frac_smooth->GetZaxis()->SetTitleFont(42);
   EffTruth_diff_frac_smooth->Draw("EXsame");
   
   TLegend *leg = new TLegend(0.55,0.77,0.8,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("EffTruth_diff_frac","nominal","lp");

   ci = TColor::GetColor("#3300cc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#3300cc");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("EffTruth_diff_frac_smooth","smoothed","lp");

   ci = TColor::GetColor("#660066");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#660066");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.2,0.87,"ATLAS");
tex->SetNDC();
   tex->SetTextFont(72);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.33,0.87,"Simulation Preliminary");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.82,"#sqrt{s} = 8 TeV, L = 20.3 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.78,"Z#rightarrow#mu#mu");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.74,"Anti-k_{t} LCW+JES R=0.4");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.7,"20 < p_{T} < 50 GeV, |#eta| < 2.4");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.66,"JVT > 0.4");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
