{
//=========Macro generated from canvas: c1/Histogram Drawing Options
//=========  (Sun May 11 02:43:06 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "Histogram Drawing Options",41,99,600,800);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.18);
   c1->SetRightMargin(0.08);
   c1->SetTopMargin(0.07);
   c1->SetBottomMargin(0.17);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderSize(0);
  
// ------------>Primitives in pad: pad1
   TPad *pad1 = new TPad("pad1", "",0,0.25,1,1);
   pad1->Draw();
   pad1->cd();
   pad1->Range(-3.567568,0.6105263,2.918919,1.136842);
   pad1->SetFillColor(0);
   pad1->SetBorderMode(0);
   pad1->SetBorderSize(1);
   pad1->SetTickx(1);
   pad1->SetTicky(1);
   pad1->SetLeftMargin(0.18);
   pad1->SetRightMargin(0.08);
   pad1->SetTopMargin(0.07);
   pad1->SetBottomMargin(0.17);
   pad1->SetFrameBorderMode(0);
   pad1->SetFrameBorderSize(0);
   pad1->SetFrameBorderMode(0);
   pad1->SetFrameBorderSize(0);
   
   TH1D *EffRecoCorrSystSmooth = new TH1D("EffRecoCorrSystSmooth","",10,-2.4,2.4);
   EffRecoCorrSystSmooth->SetBinContent(1,0.8741541);
   EffRecoCorrSystSmooth->SetBinContent(2,0.8750932);
   EffRecoCorrSystSmooth->SetBinContent(3,0.8834496);
   EffRecoCorrSystSmooth->SetBinContent(4,0.8989726);
   EffRecoCorrSystSmooth->SetBinContent(5,0.901461);
   EffRecoCorrSystSmooth->SetBinContent(6,0.8910817);
   EffRecoCorrSystSmooth->SetBinContent(7,0.8776885);
   EffRecoCorrSystSmooth->SetBinContent(8,0.8879107);
   EffRecoCorrSystSmooth->SetBinContent(9,0.8763041);
   EffRecoCorrSystSmooth->SetBinContent(10,0.881345);
   EffRecoCorrSystSmooth->SetBinError(1,0.02013984);
   EffRecoCorrSystSmooth->SetBinError(2,0.01723489);
   EffRecoCorrSystSmooth->SetBinError(3,0.01505643);
   EffRecoCorrSystSmooth->SetBinError(4,0.01539063);
   EffRecoCorrSystSmooth->SetBinError(5,0.01311721);
   EffRecoCorrSystSmooth->SetBinError(6,0.01264667);
   EffRecoCorrSystSmooth->SetBinError(7,0.01485515);
   EffRecoCorrSystSmooth->SetBinError(8,0.01509197);
   EffRecoCorrSystSmooth->SetBinError(9,0.01691175);
   EffRecoCorrSystSmooth->SetBinError(10,0.01875674);
   EffRecoCorrSystSmooth->SetMinimum(0.7);
   EffRecoCorrSystSmooth->SetMaximum(1.1);
   EffRecoCorrSystSmooth->SetEntries(50840);
   EffRecoCorrSystSmooth->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#cccccc");
   EffRecoCorrSystSmooth->SetFillColor(ci);

   ci = TColor::GetColor("#cccccc");
   EffRecoCorrSystSmooth->SetLineColor(ci);

   ci = TColor::GetColor("#cccccc");
   EffRecoCorrSystSmooth->SetMarkerColor(ci);
   EffRecoCorrSystSmooth->GetXaxis()->SetTitle("jet #eta");
   EffRecoCorrSystSmooth->GetXaxis()->SetNdivisions(505);
   EffRecoCorrSystSmooth->GetXaxis()->SetLabelFont(42);
   EffRecoCorrSystSmooth->GetXaxis()->SetLabelSize(0.05);
   EffRecoCorrSystSmooth->GetXaxis()->SetTitleSize(0.05);
   EffRecoCorrSystSmooth->GetXaxis()->SetTitleOffset(1.1);
   EffRecoCorrSystSmooth->GetXaxis()->SetTitleFont(42);
   EffRecoCorrSystSmooth->GetYaxis()->SetTitle("Efficiency");
   EffRecoCorrSystSmooth->GetYaxis()->SetNdivisions(505);
   EffRecoCorrSystSmooth->GetYaxis()->SetLabelFont(42);
   EffRecoCorrSystSmooth->GetYaxis()->SetLabelSize(0.05);
   EffRecoCorrSystSmooth->GetYaxis()->SetTitleSize(0.05);
   EffRecoCorrSystSmooth->GetYaxis()->SetTitleOffset(1.5);
   EffRecoCorrSystSmooth->GetYaxis()->SetTitleFont(42);
   EffRecoCorrSystSmooth->GetZaxis()->SetNdivisions(707);
   EffRecoCorrSystSmooth->GetZaxis()->SetLabelFont(42);
   EffRecoCorrSystSmooth->GetZaxis()->SetLabelOffset(0.015);
   EffRecoCorrSystSmooth->GetZaxis()->SetLabelSize(0.05);
   EffRecoCorrSystSmooth->GetZaxis()->SetTitleSize(0.05);
   EffRecoCorrSystSmooth->GetZaxis()->SetTitleOffset(1.1);
   EffRecoCorrSystSmooth->GetZaxis()->SetTitleFont(42);
   EffRecoCorrSystSmooth->Draw("E2");
   
   TH1D *EffRecoCorr = new TH1D("EffRecoCorr","",10,-2.4,2.4);
   EffRecoCorr->SetBinContent(1,0.8741541);
   EffRecoCorr->SetBinContent(2,0.8750932);
   EffRecoCorr->SetBinContent(3,0.8834496);
   EffRecoCorr->SetBinContent(4,0.8989726);
   EffRecoCorr->SetBinContent(5,0.901461);
   EffRecoCorr->SetBinContent(6,0.8910817);
   EffRecoCorr->SetBinContent(7,0.8776885);
   EffRecoCorr->SetBinContent(8,0.8879107);
   EffRecoCorr->SetBinContent(9,0.8763041);
   EffRecoCorr->SetBinContent(10,0.881345);
   EffRecoCorr->SetBinError(1,0.01534796);
   EffRecoCorr->SetBinError(2,0.01385829);
   EffRecoCorr->SetBinError(3,0.01259721);
   EffRecoCorr->SetBinError(4,0.01181484);
   EffRecoCorr->SetBinError(5,0.01157508);
   EffRecoCorr->SetBinError(6,0.01107842);
   EffRecoCorr->SetBinError(7,0.01131135);
   EffRecoCorr->SetBinError(8,0.01261239);
   EffRecoCorr->SetBinError(9,0.01344348);
   EffRecoCorr->SetBinError(10,0.01337733);
   EffRecoCorr->SetEntries(50840);
   EffRecoCorr->SetStats(0);

   ci = TColor::GetColor("#3300cc");
   EffRecoCorr->SetLineColor(ci);

   ci = TColor::GetColor("#3300cc");
   EffRecoCorr->SetMarkerColor(ci);
   EffRecoCorr->SetMarkerStyle(20);
   EffRecoCorr->GetXaxis()->SetTitle("jet #eta");
   EffRecoCorr->GetXaxis()->SetNdivisions(505);
   EffRecoCorr->GetXaxis()->SetLabelFont(42);
   EffRecoCorr->GetXaxis()->SetLabelSize(0.05);
   EffRecoCorr->GetXaxis()->SetTitleSize(0.05);
   EffRecoCorr->GetXaxis()->SetTitleOffset(1.1);
   EffRecoCorr->GetXaxis()->SetTitleFont(42);
   EffRecoCorr->GetYaxis()->SetTitle("Efficiency");
   EffRecoCorr->GetYaxis()->SetNdivisions(505);
   EffRecoCorr->GetYaxis()->SetLabelFont(42);
   EffRecoCorr->GetYaxis()->SetLabelSize(0.05);
   EffRecoCorr->GetYaxis()->SetTitleSize(0.05);
   EffRecoCorr->GetYaxis()->SetTitleOffset(1.5);
   EffRecoCorr->GetYaxis()->SetTitleFont(42);
   EffRecoCorr->GetZaxis()->SetNdivisions(707);
   EffRecoCorr->GetZaxis()->SetLabelFont(42);
   EffRecoCorr->GetZaxis()->SetLabelOffset(0.015);
   EffRecoCorr->GetZaxis()->SetLabelSize(0.05);
   EffRecoCorr->GetZaxis()->SetTitleSize(0.05);
   EffRecoCorr->GetZaxis()->SetTitleOffset(1.1);
   EffRecoCorr->GetZaxis()->SetTitleFont(42);
   EffRecoCorr->Draw("EXsame");
   
   TH1D *EffDataCorr = new TH1D("EffDataCorr","",10,-2.4,2.4);
   EffDataCorr->SetBinContent(1,0.8619963);
   EffDataCorr->SetBinContent(2,0.8632464);
   EffDataCorr->SetBinContent(3,0.8784223);
   EffDataCorr->SetBinContent(4,0.8832486);
   EffDataCorr->SetBinContent(5,0.8793621);
   EffDataCorr->SetBinContent(6,0.8920405);
   EffDataCorr->SetBinContent(7,0.8800443);
   EffDataCorr->SetBinContent(8,0.8698745);
   EffDataCorr->SetBinContent(9,0.8629996);
   EffDataCorr->SetBinContent(10,0.862364);
   EffDataCorr->SetBinError(1,0.003802695);
   EffDataCorr->SetBinError(2,0.003460112);
   EffDataCorr->SetBinError(3,0.003141691);
   EffDataCorr->SetBinError(4,0.002896562);
   EffDataCorr->SetBinError(5,0.002956829);
   EffDataCorr->SetBinError(6,0.002888608);
   EffDataCorr->SetBinError(7,0.002962487);
   EffDataCorr->SetBinError(8,0.003196869);
   EffDataCorr->SetBinError(9,0.003505055);
   EffDataCorr->SetBinError(10,0.003949964);
   EffDataCorr->SetEntries(149595);
   EffDataCorr->SetStats(0);
   EffDataCorr->SetMarkerStyle(20);
   EffDataCorr->GetXaxis()->SetNdivisions(505);
   EffDataCorr->GetXaxis()->SetLabelFont(42);
   EffDataCorr->GetXaxis()->SetLabelSize(0.05);
   EffDataCorr->GetXaxis()->SetTitleSize(0.05);
   EffDataCorr->GetXaxis()->SetTitleOffset(1.1);
   EffDataCorr->GetXaxis()->SetTitleFont(42);
   EffDataCorr->GetYaxis()->SetNdivisions(505);
   EffDataCorr->GetYaxis()->SetLabelFont(42);
   EffDataCorr->GetYaxis()->SetLabelSize(0.05);
   EffDataCorr->GetYaxis()->SetTitleSize(0.05);
   EffDataCorr->GetYaxis()->SetTitleOffset(1.5);
   EffDataCorr->GetYaxis()->SetTitleFont(42);
   EffDataCorr->GetZaxis()->SetNdivisions(707);
   EffDataCorr->GetZaxis()->SetLabelFont(42);
   EffDataCorr->GetZaxis()->SetLabelOffset(0.015);
   EffDataCorr->GetZaxis()->SetLabelSize(0.05);
   EffDataCorr->GetZaxis()->SetTitleSize(0.05);
   EffDataCorr->GetZaxis()->SetTitleOffset(1.1);
   EffDataCorr->GetZaxis()->SetTitleFont(42);
   EffDataCorr->Draw("EXsame");
   
   TLegend *leg = new TLegend(0.55,0.73,0.8,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("EffRecoCorrSystSmooth","Total Uncertainty","fl");

   ci = TColor::GetColor("#cccccc");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#cccccc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("EffRecoCorr","MC","lp");

   ci = TColor::GetColor("#3300cc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#3300cc");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("EffDataCorr","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.2,0.87,"ATLAS");
tex->SetNDC();
   tex->SetTextFont(72);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.33,0.87,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.82,"#sqrt{s} = 8 TeV, L = 20.3 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.78,"Sherpa Z#rightarrow#mu#mu");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.74,"Anti-k_{t} LCW+JES R=0.4");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.7,"20 < p_{T} < 50 GeV, |#eta| < 2.4");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.66,"20 < p_{T}^{ref} < 30 GeV");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.62,"JVT > 0.4");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   pad1->Modified();
   c1->cd();
  
// ------------>Primitives in pad: pad2
   pad2 = new TPad("pad2", "",0,0,1,0.25);
   pad2->Draw();
   pad2->cd();
   pad2->Range(-3.567568,0.8996226,2.918919,1.050566);
   pad2->SetFillColor(0);
   pad2->SetBorderMode(0);
   pad2->SetBorderSize(2);
   pad2->SetTickx(1);
   pad2->SetTicky(1);
   pad2->SetLeftMargin(0.18);
   pad2->SetRightMargin(0.08);
   pad2->SetTopMargin(0.07);
   pad2->SetBottomMargin(0.4);
   pad2->SetFrameBorderMode(0);
   pad2->SetFrameBorderSize(0);
   pad2->SetFrameBorderMode(0);
   pad2->SetFrameBorderSize(0);
   
   TH1D *EffRecoCorrSystSmoothuncert = new TH1D("EffRecoCorrSystSmoothuncert","",10,-2.4,2.4);
   EffRecoCorrSystSmoothuncert->SetBinContent(1,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(2,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(3,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(4,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(5,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(6,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(7,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(8,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(9,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(10,1);
   EffRecoCorrSystSmoothuncert->SetBinError(1,0.02303923);
   EffRecoCorrSystSmoothuncert->SetBinError(2,0.01969492);
   EffRecoCorrSystSmoothuncert->SetBinError(3,0.01704278);
   EffRecoCorrSystSmoothuncert->SetBinError(4,0.01712024);
   EffRecoCorrSystSmoothuncert->SetBinError(5,0.01455105);
   EffRecoCorrSystSmoothuncert->SetBinError(6,0.01419249);
   EffRecoCorrSystSmoothuncert->SetBinError(7,0.01692531);
   EffRecoCorrSystSmoothuncert->SetBinError(8,0.01699717);
   EffRecoCorrSystSmoothuncert->SetBinError(9,0.01929895);
   EffRecoCorrSystSmoothuncert->SetBinError(10,0.02128195);
   EffRecoCorrSystSmoothuncert->SetMinimum(0.96);
   EffRecoCorrSystSmoothuncert->SetMaximum(1.04);
   EffRecoCorrSystSmoothuncert->SetEntries(50850);
   EffRecoCorrSystSmoothuncert->SetStats(0);

   ci = TColor::GetColor("#999999");
   EffRecoCorrSystSmoothuncert->SetFillColor(ci);
   EffRecoCorrSystSmoothuncert->SetFillStyle(3001);

   ci = TColor::GetColor("#999999");
   EffRecoCorrSystSmoothuncert->SetLineColor(ci);

   ci = TColor::GetColor("#999999");
   EffRecoCorrSystSmoothuncert->SetMarkerColor(ci);
   EffRecoCorrSystSmoothuncert->GetXaxis()->SetNdivisions(505);
   EffRecoCorrSystSmoothuncert->GetXaxis()->SetLabelFont(42);
   EffRecoCorrSystSmoothuncert->GetXaxis()->SetLabelSize(0.15);
   EffRecoCorrSystSmoothuncert->GetXaxis()->SetTitleSize(0.15);
   EffRecoCorrSystSmoothuncert->GetXaxis()->SetTickLength(0.09);
   EffRecoCorrSystSmoothuncert->GetXaxis()->SetTitleOffset(1.1);
   EffRecoCorrSystSmoothuncert->GetXaxis()->SetTitleFont(42);
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetTitle("Data / MC");
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetNdivisions(505);
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetLabelFont(42);
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetLabelSize(0.15);
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetTitleSize(0.15);
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetTickLength(0.04);
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetTitleOffset(0.51);
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetTitleFont(42);
   EffRecoCorrSystSmoothuncert->GetZaxis()->SetNdivisions(707);
   EffRecoCorrSystSmoothuncert->GetZaxis()->SetLabelFont(42);
   EffRecoCorrSystSmoothuncert->GetZaxis()->SetLabelOffset(0.015);
   EffRecoCorrSystSmoothuncert->GetZaxis()->SetLabelSize(0.15);
   EffRecoCorrSystSmoothuncert->GetZaxis()->SetTitleSize(0.15);
   EffRecoCorrSystSmoothuncert->GetZaxis()->SetTitleOffset(1.1);
   EffRecoCorrSystSmoothuncert->GetZaxis()->SetTitleFont(42);
   EffRecoCorrSystSmoothuncert->Draw("E2");
   TLine *line = new TLine(-2.4,1,2.4,1);
   line->SetLineStyle(7);
   line->SetLineWidth(2);
   line->Draw();
   
   TH1D *EffRecoCorrSystSmoothuncert = new TH1D("EffRecoCorrSystSmoothuncert","",10,-2.4,2.4);
   EffRecoCorrSystSmoothuncert->SetBinContent(1,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(2,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(3,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(4,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(5,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(6,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(7,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(8,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(9,1);
   EffRecoCorrSystSmoothuncert->SetBinContent(10,1);
   EffRecoCorrSystSmoothuncert->SetBinError(1,0.02303923);
   EffRecoCorrSystSmoothuncert->SetBinError(2,0.01969492);
   EffRecoCorrSystSmoothuncert->SetBinError(3,0.01704278);
   EffRecoCorrSystSmoothuncert->SetBinError(4,0.01712024);
   EffRecoCorrSystSmoothuncert->SetBinError(5,0.01455105);
   EffRecoCorrSystSmoothuncert->SetBinError(6,0.01419249);
   EffRecoCorrSystSmoothuncert->SetBinError(7,0.01692531);
   EffRecoCorrSystSmoothuncert->SetBinError(8,0.01699717);
   EffRecoCorrSystSmoothuncert->SetBinError(9,0.01929895);
   EffRecoCorrSystSmoothuncert->SetBinError(10,0.02128195);
   EffRecoCorrSystSmoothuncert->SetMinimum(0.96);
   EffRecoCorrSystSmoothuncert->SetMaximum(1.04);
   EffRecoCorrSystSmoothuncert->SetEntries(50850);
   EffRecoCorrSystSmoothuncert->SetStats(0);

   ci = TColor::GetColor("#999999");
   EffRecoCorrSystSmoothuncert->SetFillColor(ci);
   EffRecoCorrSystSmoothuncert->SetFillStyle(3001);

   ci = TColor::GetColor("#999999");
   EffRecoCorrSystSmoothuncert->SetLineColor(ci);

   ci = TColor::GetColor("#999999");
   EffRecoCorrSystSmoothuncert->SetMarkerColor(ci);
   EffRecoCorrSystSmoothuncert->GetXaxis()->SetNdivisions(505);
   EffRecoCorrSystSmoothuncert->GetXaxis()->SetLabelFont(42);
   EffRecoCorrSystSmoothuncert->GetXaxis()->SetLabelSize(0.15);
   EffRecoCorrSystSmoothuncert->GetXaxis()->SetTitleSize(0.15);
   EffRecoCorrSystSmoothuncert->GetXaxis()->SetTickLength(0.09);
   EffRecoCorrSystSmoothuncert->GetXaxis()->SetTitleOffset(1.1);
   EffRecoCorrSystSmoothuncert->GetXaxis()->SetTitleFont(42);
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetTitle("Data / MC");
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetNdivisions(505);
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetLabelFont(42);
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetLabelSize(0.15);
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetTitleSize(0.15);
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetTickLength(0.04);
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetTitleOffset(0.51);
   EffRecoCorrSystSmoothuncert->GetYaxis()->SetTitleFont(42);
   EffRecoCorrSystSmoothuncert->GetZaxis()->SetNdivisions(707);
   EffRecoCorrSystSmoothuncert->GetZaxis()->SetLabelFont(42);
   EffRecoCorrSystSmoothuncert->GetZaxis()->SetLabelOffset(0.015);
   EffRecoCorrSystSmoothuncert->GetZaxis()->SetLabelSize(0.15);
   EffRecoCorrSystSmoothuncert->GetZaxis()->SetTitleSize(0.15);
   EffRecoCorrSystSmoothuncert->GetZaxis()->SetTitleOffset(1.1);
   EffRecoCorrSystSmoothuncert->GetZaxis()->SetTitleFont(42);
   EffRecoCorrSystSmoothuncert->Draw("E2same");
   
   TH1D *MCsumRatio = new TH1D("MCsumRatio","",10,-2.4,2.4);
   MCsumRatio->SetBinContent(1,0.986092);
   MCsumRatio->SetBinContent(2,0.9864622);
   MCsumRatio->SetBinContent(3,0.9943095);
   MCsumRatio->SetBinContent(4,0.9825089);
   MCsumRatio->SetBinContent(5,0.9754854);
   MCsumRatio->SetBinContent(6,1.001076);
   MCsumRatio->SetBinContent(7,1.002684);
   MCsumRatio->SetBinContent(8,0.9796869);
   MCsumRatio->SetBinContent(9,0.9848174);
   MCsumRatio->SetBinContent(10,0.9784635);
   MCsumRatio->SetBinError(1,0.02313153);
   MCsumRatio->SetBinError(2,0.01982657);
   MCsumRatio->SetBinError(3,0.01731492);
   MCsumRatio->SetBinError(4,0.01712661);
   MCsumRatio->SetBinError(5,0.01456839);
   MCsumRatio->SetBinError(6,0.01457289);
   MCsumRatio->SetBinError(7,0.01730315);
   MCsumRatio->SetBinError(8,0.0170367);
   MCsumRatio->SetBinError(9,0.01942226);
   MCsumRatio->SetBinError(10,0.02130045);
   MCsumRatio->SetEntries(28946.65);
   MCsumRatio->SetStats(0);
   MCsumRatio->SetFillColor(1);
   MCsumRatio->SetFillStyle(0);
   MCsumRatio->SetMarkerStyle(20);
   MCsumRatio->GetXaxis()->SetNdivisions(505);
   MCsumRatio->GetXaxis()->SetLabelFont(42);
   MCsumRatio->GetXaxis()->SetLabelSize(0.15);
   MCsumRatio->GetXaxis()->SetTitleSize(0.15);
   MCsumRatio->GetXaxis()->SetTickLength(0.09);
   MCsumRatio->GetXaxis()->SetTitleOffset(1.1);
   MCsumRatio->GetXaxis()->SetTitleFont(42);
   MCsumRatio->GetYaxis()->SetTitle("Data / MC");
   MCsumRatio->GetYaxis()->SetNdivisions(505);
   MCsumRatio->GetYaxis()->SetLabelFont(42);
   MCsumRatio->GetYaxis()->SetLabelSize(0.15);
   MCsumRatio->GetYaxis()->SetTitleSize(0.15);
   MCsumRatio->GetYaxis()->SetTickLength(0.04);
   MCsumRatio->GetYaxis()->SetTitleOffset(0.51);
   MCsumRatio->GetYaxis()->SetTitleFont(42);
   MCsumRatio->GetZaxis()->SetNdivisions(707);
   MCsumRatio->GetZaxis()->SetLabelFont(42);
   MCsumRatio->GetZaxis()->SetLabelOffset(0.015);
   MCsumRatio->GetZaxis()->SetLabelSize(0.15);
   MCsumRatio->GetZaxis()->SetTitleSize(0.15);
   MCsumRatio->GetZaxis()->SetTitleOffset(1.1);
   MCsumRatio->GetZaxis()->SetTitleFont(42);
   MCsumRatio->Draw("EXsame");
   pad2->Modified();
   c1->cd();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
