{
//=========Macro generated from canvas: c1/c1
//=========  (Thu Apr 17 10:52:49 2014) by ROOT version5.32/00
   TCanvas *c1 = new TCanvas("c1", "c1",597,97,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->SetHighLightColor(2);
   c1->Range(-0.5837838,-0.06254548,2.659459,0.04635571);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.18);
   c1->SetRightMargin(0.08);
   c1->SetTopMargin(0.07);
   c1->SetBottomMargin(0.17);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderSize(0);
   c1->SetFrameBorderMode(0);
   c1->SetFrameBorderSize(0);
   
   TH1D *EffTruthSyst_diff_frac = new TH1D("EffTruthSyst_diff_frac","",5,0,2.4);
   EffTruthSyst_diff_frac->SetBinContent(1,-0.008280204);
   EffTruthSyst_diff_frac->SetBinContent(2,-0.01830512);
   EffTruthSyst_diff_frac->SetBinContent(3,-0.007067207);
   EffTruthSyst_diff_frac->SetBinContent(4,-0.02220892);
   EffTruthSyst_diff_frac->SetBinContent(5,-0.0217849);
   EffTruthSyst_diff_frac->SetBinError(1,0.00697722);
   EffTruthSyst_diff_frac->SetBinError(2,0.00725929);
   EffTruthSyst_diff_frac->SetBinError(3,0.007893363);
   EffTruthSyst_diff_frac->SetBinError(4,0.009068485);
   EffTruthSyst_diff_frac->SetBinError(5,0.01027887);
   EffTruthSyst_diff_frac->SetMinimum(-0.04403228);
   EffTruthSyst_diff_frac->SetMaximum(0.03873262);
   EffTruthSyst_diff_frac->SetEntries(0.07764635);
   EffTruthSyst_diff_frac->SetStats(0);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#3300cc");
   EffTruthSyst_diff_frac->SetLineColor(ci);

   ci = TColor::GetColor("#3300cc");
   EffTruthSyst_diff_frac->SetMarkerColor(ci);
   EffTruthSyst_diff_frac->SetMarkerStyle(20);
   EffTruthSyst_diff_frac->GetXaxis()->SetTitle("jet #eta");
   EffTruthSyst_diff_frac->GetXaxis()->SetNdivisions(505);
   EffTruthSyst_diff_frac->GetXaxis()->SetLabelFont(42);
   EffTruthSyst_diff_frac->GetXaxis()->SetLabelSize(0.05);
   EffTruthSyst_diff_frac->GetXaxis()->SetTitleSize(0.05);
   EffTruthSyst_diff_frac->GetXaxis()->SetTitleOffset(1.1);
   EffTruthSyst_diff_frac->GetXaxis()->SetTitleFont(42);
   EffTruthSyst_diff_frac->GetYaxis()->SetTitle("#Delta #epsilon / #epsilon");
   EffTruthSyst_diff_frac->GetYaxis()->SetNdivisions(505);
   EffTruthSyst_diff_frac->GetYaxis()->SetLabelFont(42);
   EffTruthSyst_diff_frac->GetYaxis()->SetLabelSize(0.05);
   EffTruthSyst_diff_frac->GetYaxis()->SetTitleSize(0.05);
   EffTruthSyst_diff_frac->GetYaxis()->SetTitleOffset(1.5);
   EffTruthSyst_diff_frac->GetYaxis()->SetTitleFont(42);
   EffTruthSyst_diff_frac->GetZaxis()->SetNdivisions(707);
   EffTruthSyst_diff_frac->GetZaxis()->SetLabelFont(42);
   EffTruthSyst_diff_frac->GetZaxis()->SetLabelOffset(0.015);
   EffTruthSyst_diff_frac->GetZaxis()->SetLabelSize(0.05);
   EffTruthSyst_diff_frac->GetZaxis()->SetTitleSize(0.05);
   EffTruthSyst_diff_frac->GetZaxis()->SetTitleOffset(1.1);
   EffTruthSyst_diff_frac->GetZaxis()->SetTitleFont(42);
   EffTruthSyst_diff_frac->Draw("EX");
   
   TH1D *EffTruthSyst_diff_frac_smooth = new TH1D("EffTruthSyst_diff_frac_smooth","",5,0,2.4);
   EffTruthSyst_diff_frac_smooth->SetBinContent(1,-0.008280204);
   EffTruthSyst_diff_frac_smooth->SetBinContent(2,-0.01157241);
   EffTruthSyst_diff_frac_smooth->SetBinContent(3,-0.01480034);
   EffTruthSyst_diff_frac_smooth->SetBinContent(4,-0.01816434);
   EffTruthSyst_diff_frac_smooth->SetBinContent(5,-0.0217849);
   EffTruthSyst_diff_frac_smooth->SetBinError(1,0.00697722);
   EffTruthSyst_diff_frac_smooth->SetBinError(2,0.00725929);
   EffTruthSyst_diff_frac_smooth->SetBinError(3,0.007893363);
   EffTruthSyst_diff_frac_smooth->SetBinError(4,0.009068485);
   EffTruthSyst_diff_frac_smooth->SetBinError(5,0.01027887);
   EffTruthSyst_diff_frac_smooth->SetMinimum(-0.04403228);
   EffTruthSyst_diff_frac_smooth->SetMaximum(0.03873262);
   EffTruthSyst_diff_frac_smooth->SetEntries(0.07764635);
   EffTruthSyst_diff_frac_smooth->SetStats(0);

   ci = TColor::GetColor("#660066");
   EffTruthSyst_diff_frac_smooth->SetLineColor(ci);

   ci = TColor::GetColor("#660066");
   EffTruthSyst_diff_frac_smooth->SetMarkerColor(ci);
   EffTruthSyst_diff_frac_smooth->SetMarkerStyle(21);
   EffTruthSyst_diff_frac_smooth->GetXaxis()->SetTitle("jet #eta");
   EffTruthSyst_diff_frac_smooth->GetXaxis()->SetNdivisions(505);
   EffTruthSyst_diff_frac_smooth->GetXaxis()->SetLabelFont(42);
   EffTruthSyst_diff_frac_smooth->GetXaxis()->SetLabelSize(0.05);
   EffTruthSyst_diff_frac_smooth->GetXaxis()->SetTitleSize(0.05);
   EffTruthSyst_diff_frac_smooth->GetXaxis()->SetTitleOffset(1.1);
   EffTruthSyst_diff_frac_smooth->GetXaxis()->SetTitleFont(42);
   EffTruthSyst_diff_frac_smooth->GetYaxis()->SetTitle("#Delta #epsilon / #epsilon");
   EffTruthSyst_diff_frac_smooth->GetYaxis()->SetNdivisions(505);
   EffTruthSyst_diff_frac_smooth->GetYaxis()->SetLabelFont(42);
   EffTruthSyst_diff_frac_smooth->GetYaxis()->SetLabelSize(0.05);
   EffTruthSyst_diff_frac_smooth->GetYaxis()->SetTitleSize(0.05);
   EffTruthSyst_diff_frac_smooth->GetYaxis()->SetTitleOffset(1.5);
   EffTruthSyst_diff_frac_smooth->GetYaxis()->SetTitleFont(42);
   EffTruthSyst_diff_frac_smooth->GetZaxis()->SetNdivisions(707);
   EffTruthSyst_diff_frac_smooth->GetZaxis()->SetLabelFont(42);
   EffTruthSyst_diff_frac_smooth->GetZaxis()->SetLabelOffset(0.015);
   EffTruthSyst_diff_frac_smooth->GetZaxis()->SetLabelSize(0.05);
   EffTruthSyst_diff_frac_smooth->GetZaxis()->SetTitleSize(0.05);
   EffTruthSyst_diff_frac_smooth->GetZaxis()->SetTitleOffset(1.1);
   EffTruthSyst_diff_frac_smooth->GetZaxis()->SetTitleFont(42);
   EffTruthSyst_diff_frac_smooth->Draw("EXsame");
   
   TLegend *leg = new TLegend(0.55,0.77,0.8,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(19);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("EffTruthSyst_diff_frac","nominal","lp");

   ci = TColor::GetColor("#3300cc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#3300cc");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry=leg->AddEntry("EffTruthSyst_diff_frac_smooth","smoothed","lp");

   ci = TColor::GetColor("#660066");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);

   ci = TColor::GetColor("#660066");
   entry->SetMarkerColor(ci);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   leg->Draw();
   TLatex *   tex = new TLatex(0.2,0.87,"ATLAS");
tex->SetNDC();
   tex->SetTextFont(72);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.33,0.87,"Internal");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.04);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.82,"#sqrt{s} = 8 TeV, L = 20.3 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.78,"Z#rightarrow#mu#mu");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.74,"Anti-k_{t} LCW+JES R=0.4");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.7,"20 < p_{T} < 50 GeV, |#eta| < 2.4");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.66,"20 < p_{T}^{ref} < 30 GeV");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2,0.62,"JVT > 0.7");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
